#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Editors
#
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

# Load global aliases
alias resource="source $HOME/.zshrc"

# Load local aliases
if [[ -s ~/.aliases ]]; then
  source ~/.aliases
fi

# Sdkman
export SDKMAN_DIR="/Users/bruno/.sdkman"
[[ -s "/Users/bruno/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/bruno/.sdkman/bin/sdkman-init.sh"
